Repository functime-org/functime, pull requests merged in 2023-12, with the labels that each got.

#127 Feat/cusum filter
  docs/notebooks/changepoint_detection.ipynb
  docs/notebooks/preprocessing.ipynb
  functime/__init__.py
  functime/feature_extractors.py
  functime/plotting.py
  src/changepoint_detection/cusum.rs
  src/changepoint_detection/mod.rs
  src/feature_extraction/mod.rs
  src/lib.rs
  tests/test_changepoint_detection.py
Labels: enhancement

#134 Download typing_extensions only with python < 3.10
  docs/code/feature_engineering.py
  docs/notebooks/benchmarks.ipynb
  functime/base/forecaster.py
  functime/base/transformer.py
  functime/evaluation.py
  functime/forecasting/_ar.py
  functime/forecasting/_regressors.py
  functime/forecasting/automl.py
  functime/forecasting/elite.py
  functime/forecasting/lance.py
  functime/llm/common.py
  functime/llm/formatting.py
  functime/metrics/multi_objective.py
  functime/preprocessing.py
  functime/seasonality/calendar.py
  pyproject.toml
Labels: refactor

#142 Add polars-upgrade pre-commit hook
  .pre-commit-config.yaml
Labels: cicd

#144 style: run polars-upgrade
  functime/backtesting.py
  functime/conversion.py
  functime/preprocessing.py
  tests/test_evaluation.py
Labels: refactor

#151 feat(fractional_differencing): create frac diff plugin
  .gitignore
  Cargo.toml
  functime/feature_extractors.py
  functime/preprocessing.py
  src/lib.rs
  src/preprocessing/fractional_differencing.rs
  src/preprocessing/mod.rs
Labels: enhancement
