Repository functime-org/functime, pull requests merged in 2023-09, with the labels that each got.

#28 build: Bump polars to 0.19.1.
  docs/develop.md
  docs/forecasting.md
  docs/preprocessing.md
  functime/base/forecaster.py
  functime/conformal.py
  functime/conversion.py
  functime/cross_validation.py
  functime/evaluation.py
  functime/feature_extraction/calendar.py
  functime/forecasting/_ar.py
  functime/forecasting/_reduction.py
  functime/forecasting/elite.py
  functime/forecasting/naive.py
  functime/forecasting/snaive.py
  functime/metrics/multi_objective.py
  functime/metrics/point.py
  functime/plotting.py
  functime/preprocessing.py
  pyproject.toml
  tests/conftest.py
  tests/test_benchmarks.py
  tests/test_cross_validation.py
  tests/test_evaluation.py
  tests/test_fourier.py
  tests/test_preprocessing.py
Labels: refactor

#29 feat: Add Yeo-Johnson transformer
  docs/preprocessing.md
  functime/preprocessing.py
  tests/test_preprocessing.py
Labels: enhancement

#33 feat: tsfresh features @achasol
  functime/feature_extraction/tsfresh_achasol.py
  tests/test_tsfresh_achasol.py
Labels: enhancement

#26 feat: tsfresh features @mathieu
  functime/feature_extraction/tsfresh_mathieu.py
  tests/test_tsfresh_mathieu.py
Labels: enhancement

#32 feat: tsfresh staging
  functime/feature_extraction/tsfresh.py
  tests/__init__.py
  tests/test_tsfresh.py
Labels: enhancement

#37 feat: Support pl.Expr and pl.Series tsfresh @mathieu
  functime/feature_extraction/tsfresh.py
  tests/test_tsfresh.py
Labels: enhancement

#49 fix: tsfresh first stage perf and bugs
  functime/feature_extraction/tsfresh.py
Labels: bug

#57 fix: clean functions in tsfresh
  functime/feature_extraction/tsfresh.py
Labels: bug, refactor

#58 fix+perf: Benford correlation and entropy features
  functime/feature_extraction/tsfresh.py
Labels: bug, refactor, perf
