Repository functime-org/functime, pull requests merged in 2023-10, with the labels that each got.

#61 fix: Approx. entropy in eager mode
  functime/feature_extraction/tsfresh.py
  pyproject.toml
  tests/test_tsfresh.py
Labels: bug

#63 feat: Implement partial_autocorrelation
  functime/feature_extraction/tsfresh_pacf.py
Labels: enhancement

#64 TS Namespace + Small bug fixes + Reorg
  functime/feature_extraction/tsfresh.py
  functime/ts_feature_library.py
  tests/test_tsfresh.py
Labels: enhancement

#82 build: Decrease core build size
  docs/installation.md
  functime/forecasting/__init__.py
  pyproject.toml
Labels: build

#91 perf+test: More tsfresh updates
  functime/feature_extraction/feature_extractor.py
  functime/feature_extraction/tsfresh.py
  pyproject.toml
  src/feature_extraction/feature_extractor.rs
  src/feature_extraction/mod.rs
  src/lib.rs
  tests/test_tsfresh.py
Labels: bug, enhancement, perf

#98 feat: add `plotting.plot_entities`
  functime/plotting.py
Labels: enhancement, plotting

#101 feat(plotting): plot_* accept LazyFrames too
  functime/plotting.py
Labels: bug, plotting

#95 fix: add namespace + missing function in the namespace
  functime/feature_extraction/tsfresh.py
Labels: bug

#100 test: Streak lengths
  functime/feature_extraction/tsfresh.py
  tests/test_tsfresh.py
Labels: test
